# Generated by Django 4.0.4 on 2022-06-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionarios', '0002_diccionarios_creacion_diccionarios_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diccionarios',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
