# Generated by Django 4.0.4 on 2022-07-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionarios', '0003_alter_diccionarios_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diccionarios',
            name='creacion',
            field=models.DateTimeField(),
        ),
    ]
