# Generated by Django 4.0.4 on 2022-07-20 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionarios', '0004_alter_diccionarios_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='diccionarios',
            name='last_play',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 16, 36, 28, 827793)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diccionarios',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
