# Generated by Django 4.0.4 on 2022-07-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionarios', '0005_diccionarios_last_play_alter_diccionarios_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabras',
            name='ultima_actualizacion',
            field=models.DateTimeField(),
        ),
    ]
