# Generated by Django 4.0.4 on 2022-08-07 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diccionarios', '0006_alter_palabras_ultima_actualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDiccionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('idioma', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SharedPalabras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('significado', models.CharField(max_length=50)),
                ('shared_diccionarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diccionarios.shareddiccionarios')),
            ],
        ),
    ]
